language: ruby
rvm:
  - 2.2.5
  - 2.3.1
script: bundle exec rspec -fp spec
sudo: false
before_install:
  - gem update --system
services:
  - redis-server
notifications:
  email:
    - andrew.kreps@gmail.com
